### PR TITLE
minor formatting issues

### PR DESCRIPTION
**Pull request by minad**

### CODE REVIEW

**Comment by wenkokke** [comment]
I think you're seeing these as formatting issues because you're running the code through LaTeX—however, I'm running it through Markdown. In this scenario, the `inline code blocks` and smart dashes make sense.

**Comment by minad** [comment]
no this improves the gh rendering

tmp_26181-_20170129_2125421698783617

**Comment by wenkokke** [comment]
Woops, was looking at those diffs the wrong way around. Yup, you're right about the backticks.

**Comment by wenkokke** [comment]
I'm ok with 7d8319e377c1ba38220faa6d215eb5aff6414c23, because it actually fixes a formatting issue. The other two replace em- and en-dashes with hyphens, which isn't really right. If GitHub doesn't render these, then why not replace them with unicode em-dashes (—)?

**Comment by minad** [comment]
good idea with the unicode ones. I have to admit i was just too lazy concerning those ;)

**Comment by wenkokke** [comment]
Em-dashes shouldn't have spacing around them. This is getting a little bit messy for just a minor change.

**Comment by minad** [comment]
Sorry for that. Usually I expect maintainers to fix such nitpicks themselves. Just had the commits lying around.

**Comment by wenkokke** [comment]
Just did. Though, to be fair, 07fa7b958a9e54177f5199a7828768bc73dd888d through f4576128bdc9e9c6582a9e941012fa76042a7ab5 were your nitpicks. ^^

**Comment by minad** [comment]
Cool! I guess this was me trying to convince github to render those dashes.

**Pull request closed without merging**
